name: Deployment (staging)

on:
  push:
    branches: [ deployment ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-ruby@v1

      - name: Install GEM (ruby) SASS
        run: gem install sass

      - name: Use Node.js 14.19.1
        uses: actions/setup-node@v3
        with:
          node-version: 14.19.1

      - name: NPM Install
        run: npm install

      - name: NPM Install
        run: npm install gulp-cli -g

      - name: Gulp Build
        run: gulp build

      - name: RSync Deployments
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete --exclude="node_modules"
          path: ./
          remote_path: public_html/lanzarchitekten/wp-content/themes/wptheme.lanza
          remote_host: s094.cyon.net
          remote_user: nflxz
          remote_key: ${{ secrets.LANZ_SSH_PRIVATE_KEY }}

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test